[package]
name = "libdsp"
version.workspace = true
edition.workspace = true

[dependencies]
timecode = { path = "../timecode" }
log.workspace = true
num.workspace = true
num-complex.workspace = true
thiserror.workspace = true
rkyv.workspace = true
rand = "0.10.1"
rand_distr = "0.6.0"
bytemuck = { version = "1", features = ["derive"] }
symphonia = { version = "0.5.5", features = [ "opt-simd", "all-codecs", "all-formats" ] }
symphonia-core = "0.5.5"

[lints]
workspace = true
